[tools]
aria2 = "latest"
bat = "latest"
ccache = "latest"
cmake = "latest"
difftastic = "latest"
direnv = "latest"
dyff = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
git = "latest"
go = "latest"
hadolint = "latest"
jless = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
make = "latest"
node = "latest"
pipx = "latest"
poetry = "latest"
python = ["2.7", "latest"]
restic = "latest"
ripgrep = "latest"
rlwrap = "latest"
rust = "latest"
shellcheck = "latest"
stylua = "latest"
tmux = "latest"
usage = "latest"
zellij = "latest"
zoxide = "latest"
