[tools]
"cargo:bat" = "latest"
"cargo:difftastic" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:jless" = "latest"
"cargo:just" = "latest"
"cargo:ripgrep" = "latest"
"cargo:stylua" = "latest"
"cargo:ubi" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
cargo-binstall = "latest"
ccache = "latest"
cmake = "latest"
direnv = "latest"
dyff = "latest"
fzf = "latest"
git = "latest"
go = "latest"
hadolint = "latest"
jq = "latest"
lazygit = "latest"
make = "latest"
node = "latest"
pipx = "latest"
poetry = "latest"
python = ["2.7", "latest"]
rust = "latest"
shellcheck = "latest"
tmux = "latest"
usage = "latest"
