[tools]
"cargo:bat" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:difftastic" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-absorb" = "latest"
"cargo:just" = "latest"
"cargo:mergiraf" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:typos-cli" = "latest"
"cargo:ubi-cli" = "latest"
"cargo:zellij" = "latest"
"cargo:zoxide" = "latest"
"npm:bash-language-server" = "latest"
"pipx:basedpyright" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:tekumara/typos-lsp" = "latest"
cargo-binstall = "latest"
direnv = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
node = "latest"
pipx = "latest"
python = "3.13"
rust = "latest"
shellcheck = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
