[env]
"HOMEBREW_BUNDLE_DUMP_DESCRIBE" = "1"
"HOMEBREW_BUNDLE_FILE" = "{{ xdg_config_home }}/brew/Brewfile"
"HOMEBREW_FORCE_BREWED_CA_CERTIFICATES" = "1"
"HOMEBREW_FORCE_BREWED_CURL" = "1"
"HOMEBREW_FORCE_BREWED_GIT" = "1"
"HOMEBREW_FORCE_VENDOR_RUBY" = "1"
"HOMEBREW_NO_ANALYTICS" = "1"
"HOMEBREW_NO_AUTOREMOVE" = "1"
"HOMEBREW_NO_AUTO_UPDATE" = "1"
"HOMEBREW_NO_EMOJI" = "1"
"HOMEBREW_NO_INSECURE_REDIRECT" = "1"
"HOMEBREW_NO_INSTALL_CLEANUP" = "1"
"HOMEBREW_NO_INSTALL_UPGRADE" = "1"
