[env]
PYTHONPATH = "{{ config_root }}/bin/.local/share/9seconds/pythonpath"

# -----------------------------------------------------------------------------

[tools]
"pipx:magika" = "latest"
"github:astral-sh/ruff" = "latest"
"github:astral-sh/ty" = "latest"

# -----------------------------------------------------------------------------

[tasks."module:ensure"]
description = "Mount module"
alias = "m"
usage = '''
arg "<module>" {
  double_dash optional
  help "Name of the plug to connect to"
}
'''
wait_for = [
  "module:integrate"
]
run = "./dots ensure $usage_module"

[tasks."module:drop"]
description = "Drop module"
alias = "d"
usage = '''
arg "<module>" {
  double_dash optional
  help "Name of the plug to connect to"
}
'''
wait_for = [
  "module:integrate"
]
run = "./dots drop $usage_module"

[tasks."module:integrate"]
description = "Reintegrate modules"
alias = "r"
run = "./dots integrate"

[tasks.python]
description = "Run Python tasks"
run = [
  """fd -H --exclude .git -t file -X magika --format "%l %p" | awk '$1 == "python" {print $2}' | xargs ruff format""",
  """fd -H --exclude .git -t file -X magika --format "%l %p" | awk '$1 == "python" {print $2}' | xargs ruff check""",
  """fd -H --exclude .git -t file -X magika --format "%l %p" | awk '$1 == "python" {print $2}' | xargs ty check""",
]

[tasks.lua]
description = "Run Lua tasks"
run = "fd -e lua -H -t file -X luafmt --config luafmt.toml --level lua-jit --write"
