[tool.mypy]
python_version = "3.10"
incremental = false
cache_dir = "/dev/null"
skip_version_check = true
strict = true

[tool.isort]
profile = "black"
py_version = 310
line_length = 79
force_single_line = true
balanced_wrapping = true
use_parentheses = true
lines_before_imports = 1
lines_after_imports = 2
group_by_package = true

[tool.ruff]
line-length = 80
exclude = [
    ".git"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "EM101",
    "EM102",
    "TRY003",
    "TRY400",
    "BLE001",
    "PLW0603",
    "S301",
    "COM812",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
