[tool.mypy]
python_version = "3.10"
strict = true

[tool.isort]
profile = "black"
py_version = 310
line_length = 79
force_single_line = true
balanced_wrapping = true
use_parentheses = true
lines_before_imports = 1
lines_after_imports = 2
group_by_package = true
