line-length = 80
exclude = [
    "build",
    ".git"
]

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/
    "E", "W",
    "C90",
    "I",
    "N",
    "YTT",
    "ASYNC",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "ISC",
    "LOG",
    "PIE",
    "T20",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "ARG",
    "ERA",
    "FLY",
    "RUF",
    "PLE",
]
ignore = [
    "I001",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
