#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x


nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' && \
nvim --headless -c 'TSInstall all' -c 'TSUpdateSync' -c 'CatppuccinCompile' -c 'qall!'
