[env]
# https://mise.jdx.dev/environments/#env-directives

# https://mise.jdx.dev/environments/#env-file
_.file = [
  # Base environment variables
  { path = "{{ xdg_config_home }}/mise/env.json", redact = true },
  { path = "{{ xdg_config_home }}/mise/local-env.json", redact = true }
]
