[tools]
# Base tools
"github:jdx/usage" = "latest"
poetry = "latest"
tmux = "latest"

# Dev
"github:crate-ci/typos" = "latest"
"github:eza-community/eza" = "latest"

# Unix
"github:atanunq/viu" = "latest"
"github:binwiederhier/ntfy" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:sharkdp/fd" = "latest"
"github:skim-rs/skim" = "latest"
"github:starship/starship" = "latest"

# LSP
"github:tekumara/typos-lsp" = "latest"
"npm:bash-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:magika" = "latest"
"github:docker/docker-language-server" = "latest"

# Linters
"npm:jsonlint" = "latest"
"github:koalaman/shellcheck" = "latest"

[tools.emmylua_ls]
version = "latest"

[tools.emmylua_ls.platforms]
linux-x64 = { asset_pattern = "emmylua_ls-linux-x64.tar.gz" }
macos-arm64 = { asset_pattern = "emmylua_ls-darwin-arm64.tar.gz" }

[tools.luafmt]
version = "latest"

[tools.luafmt.platforms]
linux-x64 = { asset_pattern = "luafmt-linux-x64.tar.gz" }
macos-arm64 = { asset_pattern = "luafmt-darwin-arm64.tar.gz" }

[tool_alias]
emmylua_ls = "github:EmmyLuaLs/emmylua-analyzer-rust"
luafmt = "github:EmmyLuaLs/emmylua-analyzer-rust"
