[tasks."update"]
# https://mise.jdx.dev/tasks/toml-tasks.html
description = "Update system"
alias = "up"
run = [
  { task = "update:system:{{ os() }}"},
  {
    tasks = [
      "update:dotfiles",
      "update:nvim",
      "update:fish",
      "update:mise",
      "update:kitten",
    ]
  }
]

[tasks."update:system:linux"]
description = "Run system updates for Linux (assume Ubuntu)"
env = { DEBIAN_FRONTEND = "noninteractive" }
run = [
  "sudo apt update -q",
  "sudo apt full-upgrade --yes",
  "sudo apt autoremove --yes --purge",
]

[tasks."update:system:macos"]
description = "Run system updates for MacOS"
interactive = true
run = [
  "brew update",
  "brew upgrade --greedy-latest",
  "brew autoremove",
  "brew cleanup --prune=all --scrub",
  "rm -rf $(brew --cache)",
]

[tasks."update:dotfiles"]
description = "Update dotfiles repository"
dir = "~/.dotfiles"
wait_for = [
    "update:system:{{ os() }}"
]
run = "git pull --recurse-submodules --autostash --rebase"

[tasks."update:nvim"]
description = "Update Neovim"
wait_for = [
  "update:dotfiles",
  "update:system:{{ os() }}",
  "update:mise",
]
run = "nvim --headless +'lua vim.pack.update(nil, {force=true})' +qa"

[tasks."update:fish"]
description = "Update fish"
wait_for = [
  "update:dotfiles",
  "update:system:{{ os() }}",
]
run = "fish -ic 'fisher update'"

[tasks."update:mise"]
description = "Update mise"
wait_for = [
  "update:dotfiles",
  "update:system:{{ os() }}",
]
env = { RUSTUP_INIT_SKIP_PATH_CHECK = "1", MISE_YES="1" }
run = [
  "mise self-update 2>/dev/null || true",
  "mise plugins update",
  "mise upgrade",
  "mise prune",
  "mise reshim"
]

[tasks."update:kitten"]
description = "Update kitten"
run = "command -v kitten 2>/dev/null && kitten update-self || true"
