# vim: ts=2 sts=2 sw=2:

[task_config]
dir = "~"

[tasks."g:update"]
description = "Update system"
depends = [
  "g:update:system",
  "g:update:dotfiles",
  "g:update:nvim",
  "g:update:fish",
  "g:update:mise",
  "g:update:kitten",
]

[tasks."g:update:system"]
description = "Run system updates"
depends = [
  "g:update:system:{{ os() }}"
]

[tasks."g:update:dotfiles"]
description = "Update dotfiles"
run = [
  "git -C {{ get_env(name='9SECONDS_DOTFILES_DIR', default='~/.dotfiles') }} pull --recurse-submodules --autostash --rebase"
]

[tasks."g:update:system:linux"]
description = "Run system updates for Linux (assume Ubuntu)"
env = { DEBIAN_FRONTEND = "noninteractive" }
run = [
  "sudo apt update -q",
  "sudo apt full-upgrade --yes",
  "sudo apt autoremove --yes --purge",
]

[tasks."g:update:system:macos"]
description = "Run system updates for MacOS"
run = [
  "brew update",
  "brew upgrade --greedy-latest",
  "brew autoremove",
  "brew cleanup --prune=all --scrub",
  "rm -rf $(brew --cache)",
]

[tasks."g:update:nvim"]
description = "Update Neovim"
wait_for = [
  "g:update:dotfiles"
]
run = "nvim --headless '+Lazy! sync' +qa"

[tasks."g:update:fish"]
description = "Update fish"
wait_for = [
  "g:update:dotfiles"
]
run = "fish -ic 'fisher update'"

[tasks."g:update:mise"]
description = "Update mise"
wait_for = [
  "g:update:dotfiles"
]
env = { RUSTUP_INIT_SKIP_PATH_CHECK = "1", MISE_YES="1" }
run = [
  "mise self-update 2>/dev/null || true",
  "mise plugins update",
  "mise upgrade",
  "mise prune",
  "mise reshim"
]

[tasks."g:update:kitten"]
description = "Update kitten"
run = "command -v kitten 2>/dev/null && kitten update-self || true"
