[tool_alias]
emmylua_ls = "github:EmmyLuaLs/emmylua-analyzer-rust"
luafmt = "github:EmmyLuaLs/emmylua-analyzer-rust"

[tools]
age = "latest"
bun = "latest"
go = "latest"
node = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
sops = "latest"
uv = "latest"
usage = "latest"

neovim = "latest"

"cargo:git-absorb" = "latest"
"cargo:mergiraf" = "latest"
"cargo:shpool" = { version = "latest", os = ["linux"]}
"cargo:tree-sitter-cli" = "latest"
"github:Wilfred/difftastic" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:atanunq/viu" = "latest"
"github:binwiederhier/ntfy" = "latest"
"github:burntsushi/ripgrep" = "latest"
"github:crate-ci/typos" = "latest"
"github:eza-community/eza" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:lusingander/serie" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:skim-rs/skim" = "latest"
"github:starship/starship" = "latest"
"npm:@github/copilot" = "latest"
poetry = "latest"
tmux = "latest"

# LSP
"github:tekumara/typos-lsp" = "latest"
"npm:bash-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:magika" = "latest"
"github:docker/docker-language-server" = "latest"

# Linters
"npm:jsonlint" = "latest"
"pipx:gitlint-core" = "latest"
"github:koalaman/shellcheck" = "latest"

[tools.emmylua_ls]
version = "latest"

[tools.emmylua_ls.platforms]
linux-x64 = { asset_pattern = "emmylua_ls-linux-x64.tar.gz" }
macos-arm64 = { asset_pattern = "emmylua_ls-darwin-arm64.tar.gz" }

[tools.luafmt]
version = "latest"

[tools.luafmt.platforms]
linux-x64 = { asset_pattern = "luafmt-linux-x64.tar.gz" }
macos-arm64 = { asset_pattern = "luafmt-darwin-arm64.tar.gz" }
