[tools]
age = "latest"
bun = "latest"
go = "latest"
node = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
sops = "latest"
uv = "latest"
usage = "latest"

neovim = "latest"

"cargo:git-absorb" = "latest"
"cargo:mergiraf" = "latest"
"cargo:shpool" = { version = "latest", os = ["linux"]}
"cargo:tree-sitter-cli" = "latest"
"github:Wilfred/difftastic" = "latest"
"github:ajeetdsouza/zoxide" = "latest"
"github:atanunq/viu" = "latest"
"github:burntsushi/ripgrep" = "latest"
"github:crate-ci/typos" = "latest"
"github:eza-community/eza" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:koalaman/shellcheck" = "latest"
"github:lusingander/serie" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:skim-rs/skim" = "latest"
"github:starship/starship" = "latest"
poetry = "latest"
tmux = "latest"

# LSP
"github:LuaLS/lua-language-server" = "latest"
"github:tekumara/typos-lsp" = "latest"
"npm:bash-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:magika" = "latest"
