#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x

OPTS="--compact"

if [[ ${CHORE_F_PRUNE:-} == "1" ]]; then
  OPTS="$OPTS --prune"
fi

exec $CHORE_BIN run . restic -- forget $OPTS \
  --keep-tag "persistent" \
  --keep-last "${CHORE_P_LAST:-$BACKUPS_KEEP_LAST}" \
  --keep-daily "${CHORE_P_DAILY:-$BACKUPS_KEEP_DAILY}" \
  --keep-weekly "${CHORE_P_WEEKLY:-$BACKUPS_KEEP_WEEKLY}" \
  --keep-monthly "${CHORE_P_MONTHLY:-$BACKUPS_KEEP_DAILY}" \
  --keep-yearly "${CHORE_P_YEARLY:-$BACKUPS_KEEP_YEARLY}"
