#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x

OPTS="--no-scan --one-file-system"
OPTS="$OPTS --host ${BACKUPS_HOSTNAME:-$(hostname -fqdn)}"

if [[ ${CHORE_PL_TAG:-} != "" ]]; then
  TAGS=
  while IFS= read -r tag; do
    TAGS="$TAGS,$tag"
  done <<< "$CHORE_PL_TAG"
  OPTS="$OPTS --tag ${TAGS:1}"
fi

if [[ ${CHORE_P_EXCLUDES:-} != "" ]]; then
  OPTS="$OPTS --exclude-file $CHORE_P_EXCLUDES"
fi

exec $CHORE_BIN run . restic -- backup $OPTS "$@"
