#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x

export AWS_DEFAULT_REGION="eu-central-003"
export AWS_ACCESS_KEY_ID="$($CHORE_BIN vault get . aws_access_key_id)"
export AWS_SECRET_ACCESS_KEY="$($CHORE_BIN vault get . aws_secret_access_key)"

export GOGC="${CHORE_P_GOGC:-20}"
export RESTIC_PASSWORD_COMMAND="$CHORE_BIN vault get . repository_password"
export RESTIC_REPOSITORY="s3:s3.$AWS_DEFAULT_REGION.backblazeb2.com/$($CHORE_BIN vault get . bucket_name)"
export RESTIC_COMPRESSION="${CHORE_P_COMPRESSION:-max}"
export RESTIC_PACK_SIZE="${CHORE_P_PACK_SIZE:-32}"

CMD="$(command -v restic)"

if [[ ${CHORE_DEBUG:-} = "1" ]]; then
  CMD="$CMD --verbose=2"
fi

exec $CMD "$@"
