[tools]
bat = "latest"
ccache = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
git = "latest"
glow = "latest"
go = "latest"
lazygit = "latest"
node = "lts"
poetry = "latest"
python = ["2.7", "latest"]
restic = "latest"
ripgrep = "latest"
tmux = "latest"

[settings]
legacy_version_file = false
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '1 week'
asdf_compat = false
experimental = true
