[tools]
bat = "0.23.0"
ccache = "4.8.2"
difftastic = "0.51.1"
exa = "0.10.1"
fd = "8.7.0"
fzf = "0.42.0"
git = "2.42.0"
glow = "1.5.1"
go = "1.21.0"
lazygit = "0.40.2"
python = ["2.7.18", "3.11.5"]
ripgrep = "13.0.0"
tmux = "3.3a"

[settings]
legacy_version_file = false
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '1 week'
asdf_compat = false
