[tools]
fd = "8.7.0"
bat = "0.23.0"
ripgrep = "13.0.0"
fzf = "0.42.0"
exa = "0.10.1"
tmux = "3.3a"
difftastic = "0.51.1"
lazygit = "0.40.2"
ccache = "4.8.2"
glow = "1.5.1"

[settings]
legacy_version_file = false
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = '1 week'
asdf_compat = false
