# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# vim: set sw=2 sts=2 ts=2 et:

git:
  pagers:
    - externalDiffCommand: difft --color=always

# theme taken from
# https://github.com/Aejkatappaja/cendre/blob/main/extras/lazygit/cendre-medium.yml
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ea9875"
      - "bold"
    inactiveBorderColor:
      - "#73665b"
    searchingActiveBorderColor:
      - "#fcba81"
      - "bold"
    optionsTextColor:
      - "#ea9875"
    selectedLineBgColor:
      - "#312a28"
    inactiveViewSelectedLineBgColor:
      - "#26211f"
    cherryPickedCommitFgColor:
      - "#1d1917"
    cherryPickedCommitBgColor:
      - "#ea9875"
    markedBaseCommitFgColor:
      - "#1d1917"
    markedBaseCommitBgColor:
      - "#fcba81"
    unstagedChangesColor:
      - "#d25780"
    defaultFgColor:
      - "#e6d5c2"
