# vim: set ft=toml ts=2 sw=2 sts=2 et:

description = "Do backup cleanups"
git = "no"

[flags.prune]
description = "Run backup pruning"
required = false

[parameters.last]
description = "Always keep N last snapshots"
type = "integer"
required = false
spec = {min = "1"}

[parameters.daily]
description = "Always keep N daily snapshots"
type = "integer"
required = false
spec = {min = "0"}

[parameters.weekly]
description = "Always keep N weekly snapshots"
type = "integer"
required = false
spec = {min = "0"}

[parameters.monthly]
description = "Always keep N weekly snapshots"
type = "integer"
required = false
spec = {min = "0"}

[parameters.yearly]
description = "Always keep N yearly snapshots"
type = "integer"
required = false
spec = {min = "0"}
