#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x

OPTS="--no-scan --one-file-system"
OPTS="$OPTS --host ${BACKUPS_HOSTNAME:-$(hostname -fqdn)}"

TAGS="hostid-$(cat /etc/machine-id)"
while IFS= read -r tag; do
  if [[ $tag != "" ]]; then
    TAGS="$TAGS,$tag"
  fi
done <<< "${CHORE_P_TAG:-}"

OPTS="$OPTS --tag $TAGS"

if [[ ${CHORE_P_EXCLUDES:-} != "" ]]; then
  OPTS="$OPTS --exclude-file $CHORE_P_EXCLUDES"
fi

exec $CHORE_BIN run . restic -- backup $OPTS "$@"
