#!/bin/bash
# vim: set ft=bash sw=2 ts=2 sts=2 et:
set -eu -o pipefail

[[ ${CHORE_DEBUG:-} = "1" ]] && set -x

$CHORE_BIN run . restic -- self-update
sudo setcap cap_dac_read_search=+ep $(command -v restic)
