# vim:ft=kitty

## https://github.com/Aejkatappaja/cendre/blob/main/extras/kitty/cendre-medium.conf

background #1d1917
foreground #e6d5c2
cursor #ea9875
cursor_text_color #1d1917
selection_background #36241d
selection_foreground #e6d5c2
url_color #4e89a2
active_border_color #ea9875
inactive_border_color #3d3633
bell_border_color #f4a21c
active_tab_background #1d1917
active_tab_foreground #e6d5c2
inactive_tab_background #141110
inactive_tab_foreground #73665b

# normal
color0 #26211f
color1 #d1766e
color2 #99af6b
color3 #fcba81
color4 #58bdff
color5 #9480ba
color6 #4e89a2
color7 #a09384

# bright
color8 #73665b
color9 #d25780
color10 #43b16a
color11 #f4a21c
color12 #8bcfff
color13 #a692cd
color14 #20c9cb
color15 #e6d5c2
