directory: /media/Music/Music
library: /media/Music/beets.blb
per_disc_numbering: yes
asciify_paths: yes

plugins: chroma convert edit embedart fetchart lyrics ftintitle inline lastgenre play replaygain scrub info badfiles acousticbrainz

ui:
  color: yes

import:
  write: yes
  copy: yes
  move: no
  link: no
  resume: no

paths:
  default: Albums/$albumartist/$year - $album%aunique{}/%if{$multidisc,CD$disc/}$track. $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album ($year)%aunique{}/%if{$multidisc,CD$disc/}$track. $title

item_fields:
  multidisc: 1 if disctotal > 1 else 0

lastgenre:
  separator: ' / '

replaygain:
  backend: gstreamer

zero:
  fields: comments

badfiles:
  commands:
    flac: flac --test --silent --warnings-as-errors
    mp3: mp3val

convert:
  format: mp3_v0
  formats:
    mp3_320k:
      command: ffmpeg -i $source -y -codec:a libmp3lame -b:a 320k $dest
      extension: mp3
    mp3_v0:
      command: ffmpeg -i $source -y -codec:a libmp3lame -q:a 0 $dest
      extension: mp3
    mp3_v2:
      command: ffmpeg -i $source -y -codec:a libmp3lame -q:a 2 $dest
      extension: mp3
    mp3_v4:
      command: ffmpeg -i $source -y codec:a libmp3lame -q:a 4 $dest
      extension: mp3
    mp3_v6:
      command: ffmpeg -i $source -y codec:a libmp3lame -q:a 6 $dest
      extension: mp3
